### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by misterpeople** [Ed1123/visa_web_scraper#2] opened 2021-09-19 06:28 UTC
So i had to change creds.py.example to creds.py 
I changed your URLS to mine yet now i get this error like before:

   ```
 if has_website_changed():
  File "C:\Users\PC\Desktop\visa_web_scraper-main\selenium_scraper.py", line 54, in has_website_changed
    with open('debugging/page_source.html', 'w', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'debugging/page_source.html'
```

what should i do?

**Comment by misterpeople** [comment] 2021-09-19 06:52
I opened an archive folder and ran the code again (IDK if thats how to fix the archive problem but it worked), now it says:


```
Logged in.
Checking for changes.
A change was found. Notifying it.

C:\Users\PC\Desktop\visa_web_scraper-main>"
```

& nothing happened after that it

**Comment by Ed1123** [comment] 2021-09-19 19:09
Yeah, that part of the code should be commented out. It was meant just for debugging only. It should be fixed now.
I also added some details to the creds.py.example file.

I know the code is not that organized and well documented, but it wasn't meant for public use. I just uploaded to Github so I can work on it remotely. And I made it public just in case someone may find it useful. :)

**Closed as completed by Ed1123** 2021-09-19 19:09 UTC

**Comment by misterpeople** [comment] 2021-09-19 19:24
also chromedriver.exe was missing so i just moved it to the folder
now i get this
![212aa445e47f52b18cb53c080fdc9df4](https://user-images.githubusercontent.com/76566361/133940314-019c621b-16f0-424f-a043-37ecb41d86ae.png)

**Comment by misterpeople** [comment] 2021-09-19 19:31
i think the xpath that you wrote are not there anymore, might be?

**Comment by Ed1123** [comment] 2021-09-19 20:02
Yes, that may be one option. Another would be that the website didn't fully load before the robot try to check or the website changing layout depending of the location.
I'm not able to reproduce the error unfortunately.

**Comment by misterpeople** [comment] 2021-09-19 20:13
Well, then i got no idea anymore :)
are you interested in the offer i sent you few days ago?

**Comment by Ed1123** [comment] 2021-09-20 17:25
Yeah, unfortunately I'm not able to fix it since I don't have access to the same website and a person that doesn't have an appointment yet.
